---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sriov-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList":
      [
        {
          "resourceName": "sriov_netdevice",
          "selectors": {
                  "drivers": ["i40evf", "iavf"]
          }
        },
        {
          "resourceName": "sriov_vfio",
          "selectors": {
                  "drivers": ["vfio-pci"]
          }
        }
      ]
    }
